name: default
description: Стандартный анализ документов
prompt: |
  Проанализируй все предоставленные документы и создай краткое саммари.
  
  Выдели:
  1. Основные темы и идеи
  2. Ключевые моменты
  3. Важные выводы
  
  Отвечай на русском языке, структурированно и кратко.
